#!/bin/sh

CLASSPATH=$CLASSPATH:/home/rgarcia/programs/proguard.jar
MIDP=/home/rgarcia/programs/wtk
PRJ=starfield
MIDLET=starfield.StarfieldMIDlet
GCC=./gcc
RTJAR=/opt/j2sdk1.4.1/jre/lib/rt.jar 
PREVERIFY=/home/rgarcia/programs/wtk2.0/bin/preverify
#PREVERIFY=/home/rgarcia/programs/wtk/bin/preverify

ant -Dgcc=./gcc/src/default clean
ant -Dgcc=./gcc/src/default dist
java -classpath $CLASSPATH proguard.ProGuard -libraryjars ${MIDP}/lib/midpapi.zip -injars  bin/${PRJ}.jar -outjar bin/${PRJ}-default.jar -overloadaggressively -defaultpackage '' -keep public class $MIDLET -keep 'public class i18n.*' -keep 'public class commons.i18n.*' -keep 'public class starfield.*' -keep 'public class commons.*' 

echo -e "\n\nRe-reverifying..."
cd bin
${PREVERIFY} -classpath ${MIDP}/lib/midpapi.zip ${PRJ}-default.jar
rm ${PRJ}-default.jar

mv output/*.jar .
rm -rf output
cd ..
