#!/bin/sh

CLASSES=build/tmpclasses

ant levelparser
mkdir build/tmpclasses

cd levels/hi
LEVELS=`ls *.xml`
cd ../..

for a in $LEVELS; do
echo $a
java -classpath build/parserclasses LevelParser levels/hi/$a $CLASSES/`basename $a .xml`.evt
done
