#!/bin/sh

CLASSES=build/tmpclasses

ant levelparser
mkdir $CLASSES

cd levels/lo
LEVELS=`ls *.xml`
cd ../..

for a in $LEVELS; do
echo $a
java -classpath build/parserclasses LevelParser levels/lo/$a $CLASSES/`basename $a .xml`.evt
done
